---
- hosts: localhost
  roles:
    - { role: azure_infra, tags: infra }

- hosts: nodes
  roles:
    - { role: ocp_pre, tags: ocp }

- name: call openshift prerequisites play
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  vars:
    container_runtime_docker_storage_type: overlay2
    container_runtime_docker_storage_setup_device: /dev/sdd
  tags: ocp-pre

- name: call openshift deploy_cluster play
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
  tags: ocp-deploy

- name: install Grafana
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/openshift-grafana/config.yml
  ignore_errors: true
  tags: logging-metrics
  
- hosts: localhost
  tasks:
    - name: Install oc client
      yum:
        name: atomic-openshift-clients
        state: latest
      notify:
        - add cluster-admin
      tags: ocp-post
 
    - name: copy kube config
      fetch:
        src: ~/.kube/config
        dest: "~/.kube/"
        flat: yes
      delegate_to: "{{ groups.masters[0] }}"
      notify:
        - add cluster-admin
      tags: ocp-post
 
  handlers:
    - name: add cluster-admin
      shell: oc adm policy add-cluster-role-to-user cluster-admin admin
 
