---
# Public IPS
- name: Azure | Manage Master Public IP
  azure_rm_publicipaddress:
    resource_group: "{{ rg }}"
    state: "{{ state }}"
    name: masterPublicIP
    domain_name_label: "{{ rg_label }}"
    allocation_method: Static
  register: master_lb_ip
  when: master_lb_private_ip is not defined

# The two set_fact tasks have to be inside the blocks, they cannot be
# merged. The router_lb_ip register variable is set (and overwritten)
# even when the "when" condition is false.
- block:
    - name: Azure | Manage Router Public IP without DNS label
      azure_rm_publicipaddress:
        resource_group: "{{ rg }}"
        state: "{{ state }}"
        name: routerPublicIP
        allocation_method: Static
      register: router_lb_ip1

    - set_fact:
        router_lb_ip: "{{ router_lb_ip1.state.ip_address }}"
  when: router_lb_dns_label is not defined

- block:
    - name: Azure | Manage Router Public IP with DNS label
      azure_rm_publicipaddress:
        resource_group: "{{ rg }}"
        state: "{{ state }}"
        name: routerPublicIP
        allocation_method: Static
        domain_name_label: "{{ router_lb_dns_label }}"
      register: router_lb_ip2

    - set_fact:
        router_lb_ip: "{{ router_lb_ip2.state.ip_address }}"
  when: router_lb_dns_label is defined

# Makes this idompotent,  will fail normally since
# domain_name_label is attached to bastion-VMNic
- name: Azure | Check for existing BastionFQDN
  shell: az network public-ip show -n bastionExternalIP -g {{ rg }}  --query dnsSettings.fqdn
  register: bastion_fqdn
  ignore_errors: true

- name: Azure | Manage Bastion Public IP
  azure_rm_publicipaddress:
    resource_group: "{{ rg }}"
    name: bastionExternalIP
    domain_name_label: "{{ rg_label }}b"
    allocation_method: Static
  register: bastion_public_ip
  when: bastion_fqdn.stdout == ''

- name: Azure | Manage Bastion Public IP
  azure_rm_publicipaddress:
    resource_group: "{{ rg }}"
    state: "{{ state }}"
    name: bastionExternalIP
    domain_name_label: "{{ rg_label }}b"
    allocation_method: Static
  register: bastion_public_ip
