- name: Azure | Manage Resource Group
  azure_rm_resourcegroup:
    state: "{{ state }}"
    name: "{{ rg }}"
    location: "{{ location }}"

- name: Azure | Import azure_deploy_vnet.yml
  include_tasks: azure_deploy_vnet.yml

- name: Azure | Import azure_deploy_nsg.yml
  include_tasks: azure_deploy_nsg.yml

- name: Azure | Import azure_deploy_public_ip.yml
  include_tasks: azure_deploy_public_ip.yml

- name: Azure | Import azure_deploy_lb.yml
  include_tasks: azure_deploy_lb.yml

- name: Azure | Import azure_deploy_nic.yml
  include_tasks: azure_deploy_nic.yml

- name: Azure | Import azure_deploy_vnet_schedule_vm.yml
  include_tasks: azure_deploy_vnet_schedule_vm.yml

- name: Azure | Import azure_deploy_registry.yml
  include_tasks: azure_deploy_registry.yml




- name: remove ~/.ssh/config (WIP)
  file: path='~/.ssh/config' state=absent

- name: Azure | SSH config file exists
  stat:
    path: ~/.ssh/config
  register: sshconfig

- name: Azure | SSH config file exists with proper permissions
  file:
    state: touch
    path: ~/.ssh/config
    mode: 0600
  when: sshconfig.stat.exists == false

- name: Azure | update SSH proxy config
  blockinfile:
    create: yes
    path: ~/.ssh/config
    insertafter: EOF
    marker: "# {mark} {{ rg }} ANSIBLE MANAGED BLOCK "
    block: |
      Host bastion
        HostName     {{ rg_label }}b.{{ location }}.cloudapp.azure.com
        User         {{ admin_user }}
        IdentityFile {{ admin_privkey }}
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        LogLevel QUIET
      Host ocp*
        ProxyCommand    ssh {{ admin_user }}@bastion -W %h:%p
        IdentityFile {{ admin_privkey }}
        User         {{ admin_user }}
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        LogLevel QUIET

- name: Azure | Import create_inventory.yml
  include_tasks: create_inventory.yml
