- name: azure subscription id
  shell: az account show -o tsv --query 'id'
  register: subscription_id
  changed_when: false

- name: azure subscription name
  shell: az account show -o tsv --query 'name'
  register: subscription_name
  changed_when: false

- name: azure tenant ID
  shell: az account show -o tsv --query 'tenantId'
  register: tenant_id
  changed_when: false

- name: azure ServicePrincipal ID
  shell: az ad app show --id "http://{{sp_name}}" -o tsv --query 'appId'
  register: sp_id
  changed_when: false

- name: Ensure /etc/origin/cloudprovider exists
  file:
    state: directory
    path: /etc/origin/cloudprovider
    mode: 0660
  delegate_to: "{{ item }}"
  #  loop: "{{groups['masters']}}"

- name: template azure.conf
  template:
    src: azure.j2
    dest: /etc/origin/cloudprovider/azure.conf
    backup: yes
  delegate_to: "{{ item }}"
  #loop: "{{groups['masters']}}"

