---
- name: Azure | Import azure_deploy.yml
  include_tasks: azure_deploy.yml

- name: Azure | Import bastion.yml
  include_tasks: bastion.yml
  
- name: Azure | Import cloudprovider.yml
  include_tasks: cloudprovider.yml
  loop: "{{ groups['masters'] }}"

- name: Azure | Import subscribe.yml
  include_tasks: subscribe.yml

- name: Azure | Import storage_container.yml
  include_tasks: storage_container.yml
  loop: "{{ groups['nodes'] }}"

- name: Azure | Import storage_etcd.yml
  include_tasks: storage_etcd.yml
  loop: "{{ groups['masters'] }}"

  #- name: call openshift prerequisites play
  #import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
  #vars:
    #  container_runtime_docker_storage_type: overlay2
    #container_runtime_docker_storage_setup_device: /dev/sdd
