---
- name: Azure | Remove rh-cloud.repo
  file: 
    path: /etc/yum.repos.d/rh-cloud.repo 
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['nodes'] }}"

- name: Azure | Remove yum rhui load balancers
  file: 
    path: /etc/yum.repos.d/rhui-load-balancers 
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['nodes'] }}"

- name: Azure | Remove RHEL7 package
  yum: 
    name: RHEL7 
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['nodes'] }}"

- name: Azure | RHSM increase timeout
  lineinfile:
    dest: /etc/rhsm/rhsm.conf
    line: 'server_timeout=600'
    insertafter: '^proxy_password ='
  delegate_to: "{{ item }}"
  loop: "{{ groups['nodes'] }}"

- name: Azure | RHSM unregister
  redhat_subscription:
    state: absent
  delegate_to: "{{ item }}"
  loop: "{{ groups['nodes'] }}"

- name: Azure | RHSM register (username-passwd) Master-Infra-CNS
  redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    pasword: "{{ rhsm_pass }}"
    pool_ids: "{{ rhsm_broker_pool }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  delegate_to: "{{ item }}"
  loop: "{{ query('inventory_hostnames', 'masters:glusterfs:infra') }}"
  when:
    - rhsm_user is defined and rhsm_user != ""
    - rhsm_pass is defined and rhsm_pass != ""

- name: Azure | RHSM register (activation-key) Master-Infra-CNS 
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_key }}"
    org_id: "{{ rhsm_org }}"
    pool_ids: "{{ rhsm_broker_pool }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  delegate_to: "{{ item }}"
  loop: "{{ query('inventory_hostnames', 'masters:glusterfs:infra') }}"
  when:
    - rhsm_key is defined and rhsm_key != ""
    - rhsm_org is defined and rhsm_org != ""

- name: remove premium pool id | Master and Infra subscription only
  redhat_subscription:
    state: absent
    pool_ids: "{{ rhsm_node_pool }}"
  delegate_to: "{{ item }}"
  loop: "{{ query('inventory_hostnames', 'masters:glusterfs:infra') }}"
  when: rhsm_node_pool != rhsm_broker_pool

- name: Azure | RHSM (username-passwd) eApplication nodes 
  redhat_subscription:
    state: present
    username: "{{ rhsm_user }}"
    password: "{{ rhsm_pass }}"
    pool_ids: "{{ rhsm_node_pool }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  delegate_to: "{{ item }}"
  loop: "{{ query('inventory_hostnames', 'nodes:!masters:!glusterfs:!infra') }}"
  when:
    - rhsm_user is defined and rhsm_user != ""
    - rhsm_pass is defined and rhsm_pass != ""

- name: Azure | RHSM register (activation-key) Application nodes 
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_key }}"
    org_id: "{{ rhsm_org }}"
    pool_ids: "{{ rhsm_node_pool }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 30
  delegate_to: "{{ item }}"
  loop: "{{ query('inventory_hostnames', 'nodes:!masters:!glusterfs:!infra') }}"
  when:
    - rhsm_key is defined and rhsm_key != ""
    - rhsm_org is defined and rhsm_org != ""

- name: Azure | RHSM disable all repos
  rhsm_repository:
    name: '*'
    state: disabled
  register: repo_result
  until: repo_result is success
  retries: 10
  delay: 30
  delegate_to: "{{ item }}"
  loop: "{{ groups['nodes'] }}"

- name: Azure | RHSM enable repos for OCP
  rhsm_repository:
    name: "{{ rhsm_repos }}"
    state: enabled
  until: repo_result is success
  retries: 10
  delay: 30
  register: repo_result
  delegate_to: "{{ item }}"
  loop: "{{ groups.nodes }}"

- name: Azure | Install OCP client
  yum:
    name: atomic-openshift-clients
    state: latest
  delegate_to: "{{ item }}"
  loop: "{{ groups['masters'] }}"
