---
# tasks file for ocp_pre
# Remove in 3.10+
- name: Azure | Add azure default storage class
  block:
    - lineinfile:
        path: /usr/share/ansible/openshift-ansible/playbooks/openshift-hosted/private/openshift_default_storage_class.yml
        state: present
        regexp: ".*openshift_cloudprovider_kind.*['aws','gce','openstack','vsphere']"
        line: "    - openshift_cloudprovider_kind in ['aws','gce','openstack','vsphere','azure']"
 
  when: deploy_cns |default(true) | bool
  delegate_to: localhost
  run_once: true
  become: true
  tags: sc
 
- name: Azure | Import cloudprovider.yml
  include_tasks: cloudprovider.yml

- name: Azure | Import subscribe.yml
  include_tasks: subscribe.yml

- name: Azure | Import storage_container.yml
  include_tasks: storage_container.yml

- name: Azure | Import storage_etcd.yml
  include_tasks: storage_etcd.yml
  when: inventory_hostname in groups.masters
