- name: Create XFS filesystem
  filesystem:
    fstype: xfs
    dev: /dev/sde

- name: Set proper permissions on mount point
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0755

- name: Restore SELinux context
  command: restorecon -R /var/lib/etcd

- name: Mount XFS filesystem
  mount:
    state: mounted
    path: /var/lib/etcd
    src: /dev/sde
    fstype: xfs
