 - name: Create XFS filesystem
   filesystem:
     fstype: xfs
     dev: /dev/sdc

 - name: Set proper permissions on mount point
   file:
     path: /var/lib/origin/openshift.local.volumes
     state: directory
     mode: 0755

 - name: Restore SELinux context
   command: restorecon -R /var/lib/origin/openshift.local.volumes
   changed_when: False
 
 - name: Mount XFS filesystem
   mount:
     state: mounted
     path: /var/lib/origin/openshift.local.volumes
     src: /dev/sdc
     fstype: xfs
     opts: gquota
